CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  legalName VARCHAR(191) NOT NULL,
  licenceNumber VARCHAR(64) NOT NULL UNIQUE,
  phone VARCHAR(32) NOT NULL UNIQUE,
  passwordHash VARCHAR(191) NOT NULL,
  role VARCHAR(16) NOT NULL DEFAULT 'BUYER',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS categories (
  id INT AUTO_INCREMENT PRIMARY KEY,
  slug VARCHAR(64) NOT NULL UNIQUE,
  name VARCHAR(191) NOT NULL,
  description TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS listings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  images TEXT NOT NULL,
  startingBid DECIMAL(14,2) NOT NULL,
  currentBid DECIMAL(14,2) NOT NULL,
  bidIncrement DECIMAL(14,2) NOT NULL DEFAULT 100,
  reservePrice DECIMAL(14,2) NULL,
  `condition` VARCHAR(64) NOT NULL,
  location VARCHAR(128) NOT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'LIVE',
  startsAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  endsAt DATETIME NOT NULL,
  lastBidAt DATETIME NULL,
  categoryId INT NOT NULL,
  sellerId INT NOT NULL,
  buyerId INT NULL,
  paidAt DATETIME NULL,
  paidAmount DECIMAL(14,2) NULL,
  paymentMethod VARCHAR(32) NULL,
  bidCount INT NOT NULL DEFAULT 0,
  watchCount INT NOT NULL DEFAULT 0,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_listings_category FOREIGN KEY (categoryId) REFERENCES categories(id),
  CONSTRAINT fk_listings_seller FOREIGN KEY (sellerId) REFERENCES users(id),
  CONSTRAINT fk_listings_buyer FOREIGN KEY (buyerId) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS bids (
  id INT AUTO_INCREMENT PRIMARY KEY,
  amount DECIMAL(14,2) NOT NULL,
  listingId INT NOT NULL,
  bidderId INT NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_bids_listing FOREIGN KEY (listingId) REFERENCES listings(id) ON DELETE CASCADE,
  CONSTRAINT fk_bids_bidder FOREIGN KEY (bidderId) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS watches (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  listingId INT NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_watch (userId, listingId),
  CONSTRAINT fk_watches_user FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_watches_listing FOREIGN KEY (listingId) REFERENCES listings(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS payments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  amount DECIMAL(14,2) NOT NULL,
  method VARCHAR(32) NOT NULL,
  reference VARCHAR(64) NOT NULL,
  payerName VARCHAR(191) NOT NULL,
  payerPhone VARCHAR(32) NULL,
  last4 VARCHAR(8) NULL,
  listingId INT NOT NULL,
  buyerId INT NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_payments_listing FOREIGN KEY (listingId) REFERENCES listings(id),
  CONSTRAINT fk_payments_buyer FOREIGN KEY (buyerId) REFERENCES users(id)
);
