CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  legal_name VARCHAR(191) NOT NULL,
  licence_number VARCHAR(64) NOT NULL UNIQUE,
  phone VARCHAR(32) NOT NULL UNIQUE,
  password_hash VARCHAR(191) NOT NULL,
  role VARCHAR(16) NOT NULL DEFAULT 'BUYER',
  account_kind VARCHAR(32) NULL,
  contact_name VARCHAR(191) NOT NULL DEFAULT '',
  city VARCHAR(128) NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS categories (
  id SERIAL PRIMARY KEY,
  slug VARCHAR(64) NOT NULL UNIQUE,
  name VARCHAR(191) NOT NULL,
  description TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS listings (
  id SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  images TEXT NOT NULL,
  starting_bid DECIMAL(14,2) NOT NULL,
  current_bid DECIMAL(14,2) NOT NULL,
  bid_increment DECIMAL(14,2) NOT NULL DEFAULT 100,
  reserve_price DECIMAL(14,2) NULL,
  condition VARCHAR(64) NOT NULL,
  location VARCHAR(128) NOT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'LIVE',
  starts_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ends_at TIMESTAMPTZ NOT NULL,
  last_bid_at TIMESTAMPTZ NULL,
  category_id INT NOT NULL REFERENCES categories(id),
  seller_id INT NOT NULL REFERENCES users(id),
  buyer_id INT NULL REFERENCES users(id),
  paid_at TIMESTAMPTZ NULL,
  paid_amount DECIMAL(14,2) NULL,
  payment_method VARCHAR(32) NULL,
  bid_count INT NOT NULL DEFAULT 0,
  watch_count INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS bids (
  id SERIAL PRIMARY KEY,
  amount DECIMAL(14,2) NOT NULL,
  listing_id INT NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
  bidder_id INT NOT NULL REFERENCES users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS watches (
  id SERIAL PRIMARY KEY,
  user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  listing_id INT NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_id, listing_id)
);

CREATE TABLE IF NOT EXISTS payments (
  id SERIAL PRIMARY KEY,
  amount DECIMAL(14,2) NOT NULL,
  method VARCHAR(32) NOT NULL,
  reference VARCHAR(64) NOT NULL,
  payer_name VARCHAR(191) NOT NULL,
  payer_phone VARCHAR(32) NULL,
  last4 VARCHAR(8) NULL,
  listing_id INT NOT NULL REFERENCES listings(id),
  buyer_id INT NOT NULL REFERENCES users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
